version: '5.1.3'

services:
  postgres:
    image: postgres:16-alpine
    container_name: ostock-postgres
    environment:
      POSTGRES_DB: ostock_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      
volumes:
  postgres_data:

  # license-service:
  #   image: license:0.0.1-SNAPSHOT

  #   ports:
  #     - "8080:8080"
    
  #   environment:
  #     SPRING_PROFILES_ACTIVE: "dev"
  #     SPRING_CLOUD_CONFIG_URI: http://host.docker.internal:8071

  #   networks:
  #     backend:
  #       aliases:
  #         - "license-service"

# networks:
#   backend:
#     driver: bridge