spring.application.name=license-service
spring.profiles.active=dev
spring.config.import=optional:configserver:${SPRING_CLOUD_CONFIG_URI:http://localhost:8071}

!-- Spring actuator properties --
management.endpoints.enabled-by-default=true
management.endpoint.health.enabled=true
management.endpoint.health.show-details=always
management.health.db.enabled=false
management.health.diskspace.enabled=true